### PR TITLE
Changed step 1 to link directly to download. Changed image linking.

### PR DESCRIPTION
**Pull request by jrex003**
Made changes to step 1 to have direct link to download. Changed the linking for images. I copied how you formatted the image linking so hopefully that was done correctly.

### CODE REVIEW

**Comment by hannesdelbeke** [comment]
Because you removed the `images/` from the path, now the image example I made doesn't work anymore 😅
have a look https://github.com/techartorg/bqt/wiki/install-bqt-addon

**Comment by hannesdelbeke** [comment]
Also, I need to find a better way to review this, rather than merge in, then check the wiki if it looks good.
this is hard to catch just in text review

**Comment by hannesdelbeke** [comment]
did you move the install page outside of notes?
image

**Comment by jrex003** [comment]
I did not move it (at least I don't think I did). I noticed that it was moved on yours so I thought you did. All I did was sync to how you had it. I'll move it back into the notes folder on my next change since it looks like I still have to fix the image linking. 

For the image linking, I'm guessing I have to actually type out [[images/addon_install1.png]] instead of just [[addon_install1.png]]. In obsidian when typing in the image linking, there was an option to autocomplete, but that doesn't include in the images/ part.

**Comment by hannesdelbeke** [comment]
yes that's correct. i m looking into how this workflow can be smoothed out. will let you know if i come up with an easier workflow.

**Pull request merged**
