### PR TITLE
Wiki

### PR DESCRIPTION
**Pull request by jrex003**
Added step by step images to bqt addon install instructions. Also edited some grammar and punctuation.

### CODE REVIEW

**Comment by jrex003** [comment]
I'm not sure if I did this correctly. My edits in Obsidian are no longer showing up anymore for some reason. Not sure what happened so I'm not sure if the PR I sent contains any of my changes.

**Comment by jrex003** [comment]
Okay I think I just didn't hit commit on the changes. Was able to find the changes in stash and commit them. One thing I'm noticing from looking at my forked copy is that the images I have in Obsidian don't show up in the wiki because they're linked images in Obsidian. Do you know how to work around this?

**Comment by hannesdelbeke** [comment]
Looks great, some feedback:

- a stash will remove all your changes, and archive them locally. It's like undoing all your work but keeping a backup.
if you want to commit your changes, instead of stash you need to first `stage` your files, not `stash`.
Then commit 
then push

- don't worry about images not viewable in github, wikilinks won't work in the [github repo preview](https://github.com/jrex003/bqt/blob/wiki/notes/install%20bqt%20addon.md), so e.g. images won't show.
But they will work in the [github wiki](https://github.com/techartorg/bqt/wiki)
image

- please move all images under a folder named `image`
image
To automatically do put images in that folder in the future, i ll push a Obsidian plugin update

**Comment by jrex003** [comment]
Thanks for clarifying about `stage` vs `stash`.

I've added the images folder and moved the images over.

**Review by hannesdelbeke — APPROVED** [review]

**Comment by hannesdelbeke** [comment]
changed the PR merge to a squash and forcepushed it. to avoid the merge clutter in history

**Comment by hannesdelbeke** [comment]
your updates are live
https://github.com/techartorg/bqt/wiki/install-bqt-addon

Let's start a new PR to address some changes.
- it seems .wiki doesn't support wikilinks for images, only for links
lets change `![[ image.jpg]]` to  `[[images/image.jpg]]`
- need to add 2 spaces and a newline to show the image underneath
- added 1 example on the page.
- you link a user to a page, and then ask them to click a url. is there a shorter way to directly link them to the url?

**Pull request merged**
